[tool.black]
line-length = 120
target-version = ["py312", "py313"]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # https://docs.astral.sh/ruff/rules/missing-type-self/
    # "ANN101", # the rule has been removed
    # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    # https://docs.astral.sh/ruff/rules/commented-out-code/
    "ERA001",
    # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
    "COM812",
    # https://docs.astral.sh/ruff/rules/pytest-unittest-assertion/
    "PT009",
    # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
    # the rule may cause conflicts when used with the formatter
    "ISC001",
    # https://docs.astral.sh/ruff/rules/if-else-block-instead-of-if-exp/
    "SIM108",
]


[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.12"
python_executable = "./venv/bin/python3"
strict = true

[tool.pyright]
venvPath = "."
venv = "venv"
pythonVersion = "3.12"
pythonPlatform = "Linux"
