[tool.ruff]
select = ["ALL"]
ignore = [
    # https://beta.ruff.rs/docs/rules/missing-type-self/
    "ANN101",
    # https://beta.ruff.rs/docs/rules/#pydocstyle-d
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D106",
    "D107",
    # https://beta.ruff.rs/docs/rules/commented-out-code/
    "ERA001",
    # https://beta.ruff.rs/docs/rules/missing-trailing-comma/
    "COM812",
    # https://beta.ruff.rs/docs/rules/pytest-unittest-assertion/
    "PT009"
]

line-length = 120
target-version = "py310"

[tool.ruff.pydocstyle]
convention = "google"

[tool.black]
line-length = 120
target-version = ["py310", "py311", "py312"]
